include:
  - component: $CI_SERVER_FQDN/sndi-lille/ressources-communes/components/meta-component-js-kube/ci-js-kube@1.0.0
    inputs:
      package_manager: "npm" 
      sonar_project_key: "dsi_compas_compas-ui-v2_3395f55b-6671-4c39-9a53-6585284c1b56"
      sonar_token: "${SONAR_TOKEN}"

cypress-tests:
  image: node:latest   
  stage: build-app-and-test        
  script:
    - npm ci
    - npm run dev &                 
    - npm run e2e
  allow_failure: false