map $uri $csp_policy {
    default "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline' ; img-src 'self' data: ; worker-src 'self' blob:; object-src 'none' ; font-src 'self' data: ; connect-src 'self' https://*.insee.fr https://*.insee.test; frame-src 'self' https://*.insee.fr https://*.insee.test ;";
}

server {
    listen 8080;

    gzip on;
    gzip_vary on;
    gzip_min_length 1024;
    gzip_proxied expired no-cache no-store private auth;
    gzip_types text/plain text/css text/xml text/javascript application/x-javascript application/javascript application/xml;
    gzip_disable "MSIE [1-6]\.";

    root /usr/share/nginx/html;
    index index.html;

 

    location / {
        try_files $uri $uri/ /index.html;
        
        # Empêcher la mise en cache du fichier index.html
        add_header Cache-Control "no-cache, no-store, must-revalidate";
        add_header Content-Security-Policy $csp_policy always;
        add_header Pragma "no-cache";
        add_header Expires 0;
    }

    # Cache les assets statiques pour de meilleures performances
    location ^~ /static/ {
        try_files $uri =404;
        expires 1y;
        access_log off;
        add_header Content-Security-Policy $csp_policy always;
        add_header Cache-Control "public, max-age=31536000, immutable";
    }

    # S'assurer que les fichiers HTML, JSON et TXT ne sont pas mis en cache
    location ~* \.(html|json|txt)$ {
        try_files $uri =404;
        expires -1;
        add_header Cache-Control "no-cache, no-store, must-revalidate";
        add_header Content-Security-Policy $csp_policy always;

    }

    # Gérer les fichiers JS et CSS pour le header CSP
    location ~* \.(?:js|css|woff2?|eot|ttf|otf|svg|png|jpg|jpeg|gif|ico|webp|mp4|mp3|ogg|ogv|webm|m4v|aac|opus|wav|flac|zip|tar|gz|tgz|bz2|xz|7z)$ {
        expires 1y;
        access_log off;
        add_header Cache-Control "public, max-age=31536000, immutable";
        add_header Content-Security-Policy $csp_policy always;
    }

}