/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Api tableaux de bord Compas
 * OpenAPI spec version: 1.6.5
 */
import { fetch } from "./axiosInstance";
export interface DemandeCreationMeteo {
    idsApplication?: number[];
    valeurMeteo?: number;
    date?: string;
    commentaire?: string;
}

export interface DemandeCreationStrategieCloud {
    /** @minItems 1 */
    idsModule: number[];
    /**
     * @minimum 1
     * @maximum 3
     */
    avancement: number;
    commentaire?: string;
    envCibleProd: number;
    date: string;
}

export interface InfosSaisiesA11yToSaveDTO {
    dateMajInfosSaisies?: string;
    isDeclaration?: boolean;
    idIndicateurTypeAudit?: number;
    scoreAudit?: number;
    dateAudit?: string;
    dateDeclaration?: string;
    idModule?: number;
}

export interface ApiTagView {
    tag?: string;
    createdAt?: string;
}

export interface IhmTagView {
    tag?: string;
    createdAt?: string;
}

export interface TagsView {
    apiTagView?: ApiTagView;
    ihmTagView?: IhmTagView;
}

export interface IndicateurSecuriteView {
    applicationId?: number;
    moduleId?: number;
    nbCveCritical?: string;
    nbCveHigh?: string;
    nbCveMedium?: string;
    nbCveLow?: string;
    nbVmNonMaj?: string;
    lettreCve?: string;
    delaiVmNonMiseAjour?: string;
    lettreMajVm?: string;
    lettreGlobaleSecurite?: string;
    lettreGlobale?: string;
}

export interface CveCriticalMonthlyView {
    applicationId?: number;
    /** Premier jour du mois mesuré */
    month?: string;
    /** Nombre de CVE critiques */
    nbCveCritical?: number;
}

export interface IndicateurQualiteView {
    moduleId?: number;
    applicationId?: number;
    moduleName?: string;
    applicationName?: string;
    sndi?: string;
    domaineSndi?: string;
    domaineFonctionnel?: string;
    nbLigneCode?: string;
    nbLigneCodeNonTeste?: string;
    detteTechnique?: string;
    pourcentageCouvertureTestUnitaire?: string;
    fiabilite?: string;
    detteTechniquePast?: string;
    pourcentageCouvertureTestUnitairePast?: string;
    fiabilitePast?: string;
    lettreDetteTechnique?: string;
    lettreFiabilite?: string;
    lettreCouvertureTestUnitaire?: string;
    lettreGlobalQualite?: string;
    evolutionCouvertureTestUnitaire?: number;
    evolutionDetteTechnique?: number;
    evolutionFiabilite?: number;
    lettreGlobale?: string;
}

export interface ModuleOscar {
    idModule?: number;
    actif?: boolean;
}

export interface Meteo {
    idApplication?: number;
    appName?: string;
    sndi?: string;
    domaineSndi?: string;
    date?: string;
    valeurMeteo?: number;
    commentaire?: string;
}

export interface IndicateurModuleGreenITView {
    moduleId?: number;
    moduleName?: string;
    ramAllocated?: string;
    diskUsed?: string;
    diskAllocated?: string;
    cpuAllocated?: string;
    conso?: string;
    nbVm?: string;
    consoScore?: string;
    impactScore?: string;
    gaspillageScore?: string;
    lettreGreen?: string;
    dateMaj?: string;
}

export interface IndicateurApplicationGreenITView {
    applicationId?: number;
    applicationName?: string;
    ramAllocated?: string;
    ramMaxi?: string;
    diskAllocated?: string;
    diskUsed?: string;
    cpuAllocated?: string;
    cpuMaxi?: string;
    conso?: string;
    nbVm?: string;
    cpuUsed?: string;
    ramUsed?: string;
    s3Used?: string;
    pvcUsed?: string;
    nbPodMaxi?: string;
    ramAllocatedProd?: string;
    ramMaxiProd?: string;
    diskAllocatedProd?: string;
    diskUsedProd?: string;
    cpuAllocatedProd?: string;
    cpuMaxiProd?: string;
    consoProd?: string;
    nbVmProd?: string;
    cpuUsedProd?: string;
    ramUsedProd?: string;
    s3UsedProd?: string;
    pvcUsedProd?: string;
    nbPodMaxiProd?: string;
    consoScore?: string;
    impactScore?: string;
    gaspillageScore?: string;
    lettreGreen?: string;
    dateMaj?: string;
}

export interface Module {
    id?: number;
    nomTechnique?: string;
    applicationTechnique?: string;
    sourceCreation?: string;
    modName?: string;
    idApplication?: number;
    appName?: string;
    domaineSndi?: string;
    domaineFonctionnel?: string;
    keySonar?: string;
    sndi?: string;
    statut?: string;
    dateDerniereLivraisonEnProduction?: string;
    typeLivrable?: string;
    zoneProduction?: string;
    urlCodeSource?: string;
}

export interface Application {
    idApplication?: number;
    appName?: string;
    domaineSndi?: string;
    domaineFonctionnel?: string;
    sndi?: string;
}

export interface ApplicationTechnique {
    id?: number;
    nom?: string;
    application?: Application;
}

export interface ModuleOscarView {
    id?: number;
    nomTechnique?: string;
    nom?: string;
    statut?: string;
    zoneProduction?: string;
    projectKeySonar?: string;
    applicationTechnique?: ApplicationTechnique;
    urlCodeSource?: string;
}

export interface IndicateurDevopsView {
    moduleId?: number;
    applicationId?: number;
    moduleName?: string;
    applicationName?: string;
    sndi?: string;
    domaineSndi?: string;
    domaineFonctionnel?: string;
    nbContributorCount?: string;
    nbDeploymentCount?: string;
    distanceCount?: string;
    lettreContributorCount?: string;
    lettreDeploymentCount?: string;
    lettreDistanceCount?: string;
    lettreGlobalDevops?: string;
    lettreGlobale?: string;
}

export interface IndicateurMaturiteView {
    idApp?: number;
    idModule?: number;
    appName?: string;
    moduleName?: string;
    isModule?: boolean;
    serviceName?: string;
    domaineDev?: string;
    domaineFonctionnel?: string;
    tauxCloud?: string;
    envActuelProd?: string;
    envCibleProd?: string;
    ecartCible?: string;
    stratCloud?: string;
    commentaire?: string;
    maturiteCloud?: string;
}

export interface ApplicationTip {
    id?: number;
    nomOscar?: string;
    date?: string;
    sourceId?: number;
    conseil?: string;
    priorite?: string;
    variable?: string;
    modalite?: string;
    contrib?: number;
    answer?: string;
    pointsAppli?: number;
    delta?: number;
    createdAt?: string;
}

export interface IndicateurApplicationMaturiteCloud {
    applicationId?: number;
    maturite?: string;
    robustesse?: string;
    scoreBenefice?: string;
    scoreOrga?: string;
    scoreComplexite?: string;
    scoreTechnique?: string;
    progressionDeploy?: string;
    progressionTechnos?: string;
    progressionArchi?: string;
    progressionMateqip?: string;
    progressionDevops?: string;
    progressionCloud?: string;
}

export type IndicateursModuleA11YNotation =
    (typeof IndicateursModuleA11YNotation)[keyof typeof IndicateursModuleA11YNotation];

export const IndicateursModuleA11YNotation = {
    A: "A",
    B: "B",
    C: "C",
    D: "D",
    E: "E",
    F: "F",
    G: "G",
    H: "H",
    X: "X",
    NR: "NR",
    SO: "SO"
} as const;

export interface IndicateursModuleA11Y {
    idModule?: number;
    modName?: string;
    idApplication?: number;
    nameApplication?: string;
    sndi?: string;
    domaineSndi?: string;
    dateMajInfosSaisie?: string;
    isDeclaration?: boolean;
    typeAuditId?: number;
    typeAuditLibelle?: string;
    scoreAudit?: number;
    dateAudit?: string;
    notation?: IndicateursModuleA11YNotation;
    dateDeclaration?: string;
    nbIssueAccessibilite?: string;
    lettreIssueAccessibilite?: string;
}

export type UpdateIndicateursDevopsParams = {
    startDate?: string;
    endDate?: string;
};

export type EnvoyerAlertesParams = {
    jours?: number;
    test?: boolean;
};

export type UploadCSVBody = {
    file: Blob;
};

export type UploadKubeCSVBody = {
    file: Blob;
};

export type ImportFaitsMaturiteCloudBody = {
    file: Blob;
};

export type ImportFaitsMaturiteCloud200 = { [key: string]: number };

export type ImportApplicationTipsParams = {
    sourceId: number;
};

export type ImportApplicationTipsBody = {
    file: Blob;
};

export type ImportApplicationTips200 = { [key: string]: unknown };

export type GetIndicateurQualiteByModuleParams = {
    periode?: GetIndicateurQualiteByModulePeriode;
};

export type GetIndicateurQualiteByModulePeriode =
    (typeof GetIndicateurQualiteByModulePeriode)[keyof typeof GetIndicateurQualiteByModulePeriode];

export const GetIndicateurQualiteByModulePeriode = {
    VEILLE: "VEILLE",
    MOIS: "MOIS",
    TRIMESTRE: "TRIMESTRE",
    SEMESTRE: "SEMESTRE",
    ANNEE: "ANNEE"
} as const;

export type GetIndicateurQualiteByApplicationParams = {
    periode?: GetIndicateurQualiteByApplicationPeriode;
};

export type GetIndicateurQualiteByApplicationPeriode =
    (typeof GetIndicateurQualiteByApplicationPeriode)[keyof typeof GetIndicateurQualiteByApplicationPeriode];

export const GetIndicateurQualiteByApplicationPeriode = {
    VEILLE: "VEILLE",
    MOIS: "MOIS",
    TRIMESTRE: "TRIMESTRE",
    SEMESTRE: "SEMESTRE",
    ANNEE: "ANNEE"
} as const;

export type GetHistoryParams = {
    /**
     * Nombre de mois à remonter
     * @minimum 3
     * @maximum 12
     */
    nbMois?: number;
};

export type GetKeySonarParApplication200 = { [key: string]: string[] };

export type GetModules2Params = {
    isSynthetique?: boolean;
};

export type GetApplications2Params = {
    isSynthetique?: boolean;
};

export type GetApplicationConseilsParams = {
    nom_oscar: string;
};

export type GetAgentsIdepEmail200 = { [key: string]: string };

export type GetIndicatorsMarkdowns200 = { [key: string]: string };

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary mise à jour des indicateurs delaiMajVM en base de donnée
 */
export const updateIndicateurDelai = (options?: SecondParameter<typeof fetch<void>>) => {
    return fetch<void>({ url: `/securite/indicateurs-delaiMajVM`, method: "PUT" }, options);
};

/**
 * @summary mise à jour des indicateurs cve en base de donnée
 */
export const updateIndicateurCve = (options?: SecondParameter<typeof fetch<void>>) => {
    return fetch<void>({ url: `/securite/indicateurs-cve`, method: "PUT" }, options);
};

/**
 * @summary mise à jour des indicateurs provenant de sonar
 */
export const updateIndicateursSonar = (options?: SecondParameter<typeof fetch<void>>) => {
    return fetch<void>({ url: `/qualite/indicateurs-sonar`, method: "PUT" }, options);
};

/**
 * @summary Mettre à jour les modules de Compas à partir d'Oscar
 */
export const miseAjourModule = (options?: SecondParameter<typeof fetch<void>>) => {
    return fetch<void>({ url: `/module-oscar/mise-a-jour`, method: "PUT" }, options);
};

/**
 * @summary mise à jour des indicateurs devops en base de donnée
 */
export const updateIndicateursDevops = (
    params?: UpdateIndicateursDevopsParams,
    options?: SecondParameter<typeof fetch<void>>
) => {
    return fetch<void>({ url: `/devops/indicateurs-devops`, method: "PUT", params }, options);
};

/**
 * @summary Insertion des AA11y de sonar dans la bdd infosSaisies
 */
export const majNbIssueSonarAccessibitlite = (options?: SecondParameter<typeof fetch<void>>) => {
    return fetch<void>({ url: `/a11y/issues-accessibility`, method: "PUT" }, options);
};

/**
 * @summary Lister toutes les applications et leur éventuelle météo
 */
export const listerApplicationsMeteo = (options?: SecondParameter<typeof fetch<Meteo[]>>) => {
    return fetch<Meteo[]>({ url: `/meteo`, method: "GET" }, options);
};

/**
 * @summary Création d'une météo pour une application. Renvoie les ids des TableFaits créés.
 */
export const creerMeteo = (
    demandeCreationMeteo: DemandeCreationMeteo,
    options?: SecondParameter<typeof fetch<number[]>>
) => {
    return fetch<number[]>(
        {
            url: `/meteo`,
            method: "POST",
            headers: { "Content-Type": "application/json" },
            data: demandeCreationMeteo
        },
        options
    );
};

/**
 * @summary Envoie des mails d'alertes aux responsables des apps de chaque sndi
 */
export const envoyerAlertes = (
    params?: EnvoyerAlertesParams,
    options?: SecondParameter<typeof fetch<void>>
) => {
    return fetch<void>({ url: `/meteo/alertes`, method: "POST", params }, options);
};

export const uploadCSV = (
    uploadCSVBody: UploadCSVBody,
    options?: SecondParameter<typeof fetch<Blob>>
) => {
    const formData = new FormData();
    formData.append(`file`, uploadCSVBody.file);

    return fetch<Blob>(
        { url: `/kpi-green/modules/upload`, method: "POST", data: formData, responseType: "blob" },
        options
    );
};

export const uploadKubeCSV = (
    uploadKubeCSVBody: UploadKubeCSVBody,
    options?: SecondParameter<typeof fetch<Blob>>
) => {
    const formData = new FormData();
    formData.append(`file`, uploadKubeCSVBody.file);

    return fetch<Blob>(
        { url: `/kpi-green/modules/upload/kube`, method: "POST", data: formData, responseType: "blob" },
        options
    );
};

/**
 * @summary Saisie de la maturité cloud
 */
export const saisirStrategieCloud = (
    demandeCreationStrategieCloud: DemandeCreationStrategieCloud,
    options?: SecondParameter<typeof fetch<number[]>>
) => {
    return fetch<number[]>(
        {
            url: `/cloud/strategie`,
            method: "POST",
            headers: { "Content-Type": "application/json" },
            data: demandeCreationStrategieCloud
        },
        options
    );
};

export const importFaitsMaturiteCloud = (
    importFaitsMaturiteCloudBody: ImportFaitsMaturiteCloudBody,
    options?: SecondParameter<typeof fetch<Blob>>
) => {
    const formData = new FormData();
    formData.append(`file`, importFaitsMaturiteCloudBody.file);

    return fetch<Blob>(
        { url: `/cloud/maturite-cloud/import`, method: "POST", data: formData, responseType: "blob" },
        options
    );
};

export const importApplicationTips = (
    importApplicationTipsBody: ImportApplicationTipsBody,
    params: ImportApplicationTipsParams,
    options?: SecondParameter<typeof fetch<Blob>>
) => {
    const formData = new FormData();
    formData.append(`file`, importApplicationTipsBody.file);

    return fetch<Blob>(
        { url: `/cloud/conseils/import`, method: "POST", data: formData, params, responseType: "blob" },
        options
    );
};

/**
 * @summary Création / update des informations saisie pour un module. Renvoie l'id des infosSaisies
 */
export const majInfosSaisiesA11Y = (
    infosSaisiesA11yToSaveDTO: InfosSaisiesA11yToSaveDTO,
    options?: SecondParameter<typeof fetch<Blob>>
) => {
    return fetch<Blob>(
        {
            url: `/a11y`,
            method: "POST",
            headers: { "Content-Type": "application/json" },
            data: infosSaisiesA11yToSaveDTO,
            responseType: "blob"
        },
        options
    );
};

export const getTags = (options?: SecondParameter<typeof fetch<TagsView>>) => {
    return fetch<TagsView>({ url: `/tags`, method: "GET" }, options);
};

export const getIndicateurSecuriteByModule = (
    options?: SecondParameter<typeof fetch<IndicateurSecuriteView[]>>
) => {
    return fetch<IndicateurSecuriteView[]>({ url: `/securite/modules`, method: "GET" }, options);
};

export const getIndicateurSecuriteByApplication = (
    options?: SecondParameter<typeof fetch<IndicateurSecuriteView[]>>
) => {
    return fetch<IndicateurSecuriteView[]>({ url: `/securite/applications`, method: "GET" }, options);
};

/**
 * @summary CVE critiques par application et par mois (mesures du 1er du mois)
 */
export const getCveCriticalMonthly = (
    options?: SecondParameter<typeof fetch<CveCriticalMonthlyView[]>>
) => {
    return fetch<CveCriticalMonthlyView[]>(
        { url: `/securite/applications/cve-critical/monthly`, method: "GET" },
        options
    );
};

export const getIndicateurQualiteByModule = (
    params?: GetIndicateurQualiteByModuleParams,
    options?: SecondParameter<typeof fetch<IndicateurQualiteView[]>>
) => {
    return fetch<IndicateurQualiteView[]>({ url: `/qualite/modules`, method: "GET", params }, options);
};

export const getIndicateurQualiteByApplication = (
    params?: GetIndicateurQualiteByApplicationParams,
    options?: SecondParameter<typeof fetch<IndicateurQualiteView[]>>
) => {
    return fetch<IndicateurQualiteView[]>(
        { url: `/qualite/applications`, method: "GET", params },
        options
    );
};

/**
 * @summary Obtenir tous les modules actifs
 */
export const getModuleActif = (options?: SecondParameter<typeof fetch<ModuleOscar[]>>) => {
    return fetch<ModuleOscar[]>({ url: `/module-oscar/find-module-actif`, method: "GET" }, options);
};

/**
 * @summary Obtenir tous les modules
 */
export const getAllUsers = (options?: SecondParameter<typeof fetch<ModuleOscar[]>>) => {
    return fetch<ModuleOscar[]>({ url: `/module-oscar/find-all`, method: "GET" }, options);
};

/**
 * @summary Lister les dernières données météo sur une fenêtre de X mois
 */
export const getHistory = (
    params?: GetHistoryParams,
    options?: SecondParameter<typeof fetch<Meteo[]>>
) => {
    return fetch<Meteo[]>({ url: `/meteo/history`, method: "GET", params }, options);
};

/**
 * @summary Lister les applications dont la dernière météo date d'au moins 23 jours
 */
export const listerApplicationsMeteoAnciennes = (options?: SecondParameter<typeof fetch<Meteo[]>>) => {
    return fetch<Meteo[]>({ url: `/meteo/anciennes`, method: "GET" }, options);
};

/**
 * @summary Lister les applications dont la dernière météo date d'au moins X jours
 */
export const listerApplicationsMeteoAnciennesParam = (
    jours: number,
    options?: SecondParameter<typeof fetch<Meteo[]>>
) => {
    return fetch<Meteo[]>({ url: `/meteo/anciennes/${jours}`, method: "GET" }, options);
};

export const getModules = (options?: SecondParameter<typeof fetch<IndicateurModuleGreenITView[]>>) => {
    return fetch<IndicateurModuleGreenITView[]>({ url: `/kpi-green/modules`, method: "GET" }, options);
};

export const getIndicateursGreenIT = (
    moduleId: number,
    options?: SecondParameter<typeof fetch<IndicateurModuleGreenITView>>
) => {
    return fetch<IndicateurModuleGreenITView>(
        { url: `/kpi-green/modules/${moduleId}`, method: "GET" },
        options
    );
};

export const getApplications = (
    options?: SecondParameter<typeof fetch<IndicateurApplicationGreenITView[]>>
) => {
    return fetch<IndicateurApplicationGreenITView[]>(
        { url: `/kpi-green/applications`, method: "GET" },
        options
    );
};

export const getNombreVirtualMachine = (
    applicationId: number,
    options?: SecondParameter<typeof fetch<IndicateurApplicationGreenITView>>
) => {
    return fetch<IndicateurApplicationGreenITView>(
        { url: `/kpi-green/applications/${applicationId}`, method: "GET" },
        options
    );
};

/**
 * @summary liste des modules d'oscar sans feign
 */
export const getModules1 = (options?: SecondParameter<typeof fetch<Module[]>>) => {
    return fetch<Module[]>({ url: `/get-modules`, method: "GET" }, options);
};

/**
 * @summary liste des modules d'oscar sans feign
 */
export const getKeySonarParApplication = (
    options?: SecondParameter<typeof fetch<GetKeySonarParApplication200>>
) => {
    return fetch<GetKeySonarParApplication200>(
        { url: `/get-key-sonar-applications`, method: "GET" },
        options
    );
};

/**
 * @summary liste des applications d'oscar sans feign
 */
export const getApplications1 = (options?: SecondParameter<typeof fetch<Application[]>>) => {
    return fetch<Application[]>({ url: `/get-applications`, method: "GET" }, options);
};

/**
 * @summary liste des modules d'oscar
 */
export const getAllModules = (options?: SecondParameter<typeof fetch<ModuleOscarView[]>>) => {
    return fetch<ModuleOscarView[]>({ url: `/get-all-modules`, method: "GET" }, options);
};

export const getModules2 = (
    params?: GetModules2Params,
    options?: SecondParameter<typeof fetch<IndicateurDevopsView[]>>
) => {
    return fetch<IndicateurDevopsView[]>({ url: `/devops/modules`, method: "GET", params }, options);
};

export const getApplications2 = (
    params?: GetApplications2Params,
    options?: SecondParameter<typeof fetch<IndicateurDevopsView[]>>
) => {
    return fetch<IndicateurDevopsView[]>(
        { url: `/devops/applications`, method: "GET", params },
        options
    );
};

/**
 * @summary Récupération des indicateurs de maturité cloud
 */
export const getIndicateur = (
    options?: SecondParameter<typeof fetch<IndicateurMaturiteView[] | void>>
) => {
    return fetch<IndicateurMaturiteView[] | void>({ url: `/cloud/indicateur`, method: "GET" }, options);
};

export const getApplicationConseils = (
    params: GetApplicationConseilsParams,
    options?: SecondParameter<typeof fetch<ApplicationTip[]>>
) => {
    return fetch<ApplicationTip[]>({ url: `/cloud/conseils`, method: "GET", params }, options);
};

export const getMaturiteCloud = (
    options?: SecondParameter<typeof fetch<IndicateurApplicationMaturiteCloud[]>>
) => {
    return fetch<IndicateurApplicationMaturiteCloud[]>(
        { url: `/cloud/applications`, method: "GET" },
        options
    );
};

export const getRgaByApplicationId = (id: number, options?: SecondParameter<typeof fetch<string>>) => {
    return fetch<string>({ url: `/application/${id}/rga`, method: "GET" }, options);
};

export const getAgentsIdepEmail = (options?: SecondParameter<typeof fetch<GetAgentsIdepEmail200>>) => {
    return fetch<GetAgentsIdepEmail200>({ url: `/api/agents`, method: "GET" }, options);
};

/**
 * Retourne une map où la clé est le nom de l'indicateur et la valeur est son contenu en markdown
 * @summary Récupération des indicateurs en format markdown
 */
export const getIndicatorsMarkdowns = (
    options?: SecondParameter<typeof fetch<GetIndicatorsMarkdowns200>>
) => {
    return fetch<GetIndicatorsMarkdowns200>({ url: `/accueil/indicators`, method: "GET" }, options);
};

/**
 * @summary Lister tous les modules et informations accessibilité pour les IHM
 */
export const listerModulesA11y = (options?: SecondParameter<typeof fetch<IndicateursModuleA11Y[]>>) => {
    return fetch<IndicateursModuleA11Y[]>({ url: `/a11y/modules`, method: "GET" }, options);
};

/**
 * @summary Lister tous les modules et informations accessibilité
 */
export const listerModulesALL11y = (
    options?: SecondParameter<typeof fetch<IndicateursModuleA11Y[]>>
) => {
    return fetch<IndicateursModuleA11Y[]>({ url: `/a11y/modules-all`, method: "GET" }, options);
};

/**
 * @summary Lister tous les modules et informations accessibilité
 */
export const listerApplicationA11y = (
    options?: SecondParameter<typeof fetch<IndicateursModuleA11Y[]>>
) => {
    return fetch<IndicateursModuleA11Y[]>({ url: `/a11y/applications`, method: "GET" }, options);
};

export type UpdateIndicateurDelaiResult = NonNullable<Awaited<ReturnType<typeof updateIndicateurDelai>>>;
export type UpdateIndicateurCveResult = NonNullable<Awaited<ReturnType<typeof updateIndicateurCve>>>;
export type UpdateIndicateursSonarResult = NonNullable<
    Awaited<ReturnType<typeof updateIndicateursSonar>>
>;
export type MiseAjourModuleResult = NonNullable<Awaited<ReturnType<typeof miseAjourModule>>>;
export type UpdateIndicateursDevopsResult = NonNullable<
    Awaited<ReturnType<typeof updateIndicateursDevops>>
>;
export type MajNbIssueSonarAccessibitliteResult = NonNullable<
    Awaited<ReturnType<typeof majNbIssueSonarAccessibitlite>>
>;
export type ListerApplicationsMeteoResult = NonNullable<
    Awaited<ReturnType<typeof listerApplicationsMeteo>>
>;
export type CreerMeteoResult = NonNullable<Awaited<ReturnType<typeof creerMeteo>>>;
export type EnvoyerAlertesResult = NonNullable<Awaited<ReturnType<typeof envoyerAlertes>>>;
export type UploadCSVResult = NonNullable<Awaited<ReturnType<typeof uploadCSV>>>;
export type UploadKubeCSVResult = NonNullable<Awaited<ReturnType<typeof uploadKubeCSV>>>;
export type SaisirStrategieCloudResult = NonNullable<Awaited<ReturnType<typeof saisirStrategieCloud>>>;
export type ImportFaitsMaturiteCloudResult = NonNullable<
    Awaited<ReturnType<typeof importFaitsMaturiteCloud>>
>;
export type ImportApplicationTipsResult = NonNullable<Awaited<ReturnType<typeof importApplicationTips>>>;
export type MajInfosSaisiesA11YResult = NonNullable<Awaited<ReturnType<typeof majInfosSaisiesA11Y>>>;
export type GetTagsResult = NonNullable<Awaited<ReturnType<typeof getTags>>>;
export type GetIndicateurSecuriteByModuleResult = NonNullable<
    Awaited<ReturnType<typeof getIndicateurSecuriteByModule>>
>;
export type GetIndicateurSecuriteByApplicationResult = NonNullable<
    Awaited<ReturnType<typeof getIndicateurSecuriteByApplication>>
>;
export type GetCveCriticalMonthlyResult = NonNullable<Awaited<ReturnType<typeof getCveCriticalMonthly>>>;
export type GetIndicateurQualiteByModuleResult = NonNullable<
    Awaited<ReturnType<typeof getIndicateurQualiteByModule>>
>;
export type GetIndicateurQualiteByApplicationResult = NonNullable<
    Awaited<ReturnType<typeof getIndicateurQualiteByApplication>>
>;
export type GetModuleActifResult = NonNullable<Awaited<ReturnType<typeof getModuleActif>>>;
export type GetAllUsersResult = NonNullable<Awaited<ReturnType<typeof getAllUsers>>>;
export type GetHistoryResult = NonNullable<Awaited<ReturnType<typeof getHistory>>>;
export type ListerApplicationsMeteoAnciennesResult = NonNullable<
    Awaited<ReturnType<typeof listerApplicationsMeteoAnciennes>>
>;
export type ListerApplicationsMeteoAnciennesParamResult = NonNullable<
    Awaited<ReturnType<typeof listerApplicationsMeteoAnciennesParam>>
>;
export type GetModulesResult = NonNullable<Awaited<ReturnType<typeof getModules>>>;
export type GetIndicateursGreenITResult = NonNullable<Awaited<ReturnType<typeof getIndicateursGreenIT>>>;
export type GetApplicationsResult = NonNullable<Awaited<ReturnType<typeof getApplications>>>;
export type GetNombreVirtualMachineResult = NonNullable<
    Awaited<ReturnType<typeof getNombreVirtualMachine>>
>;
export type GetModules1Result = NonNullable<Awaited<ReturnType<typeof getModules1>>>;
export type GetKeySonarParApplicationResult = NonNullable<
    Awaited<ReturnType<typeof getKeySonarParApplication>>
>;
export type GetApplications1Result = NonNullable<Awaited<ReturnType<typeof getApplications1>>>;
export type GetAllModulesResult = NonNullable<Awaited<ReturnType<typeof getAllModules>>>;
export type GetModules2Result = NonNullable<Awaited<ReturnType<typeof getModules2>>>;
export type GetApplications2Result = NonNullable<Awaited<ReturnType<typeof getApplications2>>>;
export type GetIndicateurResult = NonNullable<Awaited<ReturnType<typeof getIndicateur>>>;
export type GetApplicationConseilsResult = NonNullable<
    Awaited<ReturnType<typeof getApplicationConseils>>
>;
export type GetMaturiteCloudResult = NonNullable<Awaited<ReturnType<typeof getMaturiteCloud>>>;
export type GetRgaByApplicationIdResult = NonNullable<Awaited<ReturnType<typeof getRgaByApplicationId>>>;
export type GetAgentsIdepEmailResult = NonNullable<Awaited<ReturnType<typeof getAgentsIdepEmail>>>;
export type GetIndicatorsMarkdownsResult = NonNullable<
    Awaited<ReturnType<typeof getIndicatorsMarkdowns>>
>;
export type ListerModulesA11yResult = NonNullable<Awaited<ReturnType<typeof listerModulesA11y>>>;
export type ListerModulesALL11yResult = NonNullable<Awaited<ReturnType<typeof listerModulesALL11y>>>;
export type ListerApplicationA11yResult = NonNullable<Awaited<ReturnType<typeof listerApplicationA11y>>>;
