export const CSV_HEADERS = [
    "Nom d'application",
    "Nom de module",
    "Service dev.",
    "Domaine dev.",
    "Domaine fonctionnel",
    "Synthèse Qualité",
    "Synthèse DevOps",
    "Niveau couverture test",
    "% couverture test",
    "Niveau dette technique",
    "Dette technique (jours)",
    "Niveau fiabilité",
    "Niveau CVE",
    "CVE critique",
    "CVE élevé",
    "CVE moyen",
    "CVE faible",
    "Niveau fraîcheur MEP",
    "Dernière MEP (nombre de jours)",
    "Date de la dernière météo",
    "Météo",
    "Commentaire météo",
    "Accessibilité",
    "Score accessibilité",
    "Niveau GreenIT",
    "Conso GreenIT (brute)",
    "Score conso GreenIT (normalisé)",
    "Score impact GreenIT (normalisé)",
    "Score gaspillage GreenIT",
    "Nb VM",
    "CPU alloué",
    "CPU maxi",
    "RAM allouée",
    "RAM maxi",
    "Disque alloué",
    "Disque utilisé",
    "Nb VM (prod)",
    "CPU alloué (prod)",
    "CPU maxi (prod)",
    "RAM allouée (prod)",
    "RAM maxi (prod)",
    "Disque alloué (prod)",
    "Disque utilisé (prod)",
    "Conso GreenIT prod (brute)"
] as const;
