/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PageNameRouteImport } from './routes/$pageName'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SaisieStrategiecloudRouteImport } from './routes/saisie/strategiecloud'
import { Route as SaisieMeteoRouteImport } from './routes/saisie/meteo'
import { Route as SaisieAccessibilitChar233RouteImport } from './routes/saisie/accessibilité'
import { Route as IndicateurStrategieCloudTableRouteImport } from './routes/indicateur/strategieCloudTable'
import { Route as IndicateurSecuriteTableRouteImport } from './routes/indicateur/securiteTable'
import { Route as IndicateurQualiteTableRouteImport } from './routes/indicateur/qualiteTable'
import { Route as IndicateurMeteoTableRouteImport } from './routes/indicateur/meteoTable'
import { Route as IndicateurMainIndicatorsRouteImport } from './routes/indicateur/mainIndicators'
import { Route as IndicateurGreenITTableRouteImport } from './routes/indicateur/greenITTable'
import { Route as IndicateurDevopsTableRouteImport } from './routes/indicateur/devopsTable'
import { Route as IndicateurAccessibiliteTableRouteImport } from './routes/indicateur/accessibiliteTable'
import { Route as DashboardSyntheseRouteImport } from './routes/dashboard/synthese'
import { Route as DashboardSecuriteRouteImport } from './routes/dashboard/securite'
import { Route as DashboardQualiteRouteImport } from './routes/dashboard/qualite'
import { Route as DashboardOverviewRouteImport } from './routes/dashboard/overview'
import { Route as DashboardMeteoRouteImport } from './routes/dashboard/meteo'
import { Route as DashboardMaturiteRouteImport } from './routes/dashboard/maturite'
import { Route as DashboardGreenitRouteImport } from './routes/dashboard/greenit'
import { Route as DashboardDevopsRouteImport } from './routes/dashboard/devops'
import { Route as DashboardAccessibiliteRouteImport } from './routes/dashboard/accessibilite'

const PageNameRoute = PageNameRouteImport.update({
  id: '/$pageName',
  path: '/$pageName',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SaisieStrategiecloudRoute = SaisieStrategiecloudRouteImport.update({
  id: '/saisie/strategiecloud',
  path: '/saisie/strategiecloud',
  getParentRoute: () => rootRouteImport,
} as any)
const SaisieMeteoRoute = SaisieMeteoRouteImport.update({
  id: '/saisie/meteo',
  path: '/saisie/meteo',
  getParentRoute: () => rootRouteImport,
} as any)
const SaisieAccessibilitChar233Route =
  SaisieAccessibilitChar233RouteImport.update({
    id: '/saisie/accessibilité',
    path: '/saisie/accessibilité',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndicateurStrategieCloudTableRoute =
  IndicateurStrategieCloudTableRouteImport.update({
    id: '/indicateur/strategieCloudTable',
    path: '/indicateur/strategieCloudTable',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndicateurSecuriteTableRoute = IndicateurSecuriteTableRouteImport.update({
  id: '/indicateur/securiteTable',
  path: '/indicateur/securiteTable',
  getParentRoute: () => rootRouteImport,
} as any)
const IndicateurQualiteTableRoute = IndicateurQualiteTableRouteImport.update({
  id: '/indicateur/qualiteTable',
  path: '/indicateur/qualiteTable',
  getParentRoute: () => rootRouteImport,
} as any)
const IndicateurMeteoTableRoute = IndicateurMeteoTableRouteImport.update({
  id: '/indicateur/meteoTable',
  path: '/indicateur/meteoTable',
  getParentRoute: () => rootRouteImport,
} as any)
const IndicateurMainIndicatorsRoute =
  IndicateurMainIndicatorsRouteImport.update({
    id: '/indicateur/mainIndicators',
    path: '/indicateur/mainIndicators',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndicateurGreenITTableRoute = IndicateurGreenITTableRouteImport.update({
  id: '/indicateur/greenITTable',
  path: '/indicateur/greenITTable',
  getParentRoute: () => rootRouteImport,
} as any)
const IndicateurDevopsTableRoute = IndicateurDevopsTableRouteImport.update({
  id: '/indicateur/devopsTable',
  path: '/indicateur/devopsTable',
  getParentRoute: () => rootRouteImport,
} as any)
const IndicateurAccessibiliteTableRoute =
  IndicateurAccessibiliteTableRouteImport.update({
    id: '/indicateur/accessibiliteTable',
    path: '/indicateur/accessibiliteTable',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardSyntheseRoute = DashboardSyntheseRouteImport.update({
  id: '/dashboard/synthese',
  path: '/dashboard/synthese',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSecuriteRoute = DashboardSecuriteRouteImport.update({
  id: '/dashboard/securite',
  path: '/dashboard/securite',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardQualiteRoute = DashboardQualiteRouteImport.update({
  id: '/dashboard/qualite',
  path: '/dashboard/qualite',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardOverviewRoute = DashboardOverviewRouteImport.update({
  id: '/dashboard/overview',
  path: '/dashboard/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardMeteoRoute = DashboardMeteoRouteImport.update({
  id: '/dashboard/meteo',
  path: '/dashboard/meteo',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardMaturiteRoute = DashboardMaturiteRouteImport.update({
  id: '/dashboard/maturite',
  path: '/dashboard/maturite',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardGreenitRoute = DashboardGreenitRouteImport.update({
  id: '/dashboard/greenit',
  path: '/dashboard/greenit',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDevopsRoute = DashboardDevopsRouteImport.update({
  id: '/dashboard/devops',
  path: '/dashboard/devops',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAccessibiliteRoute = DashboardAccessibiliteRouteImport.update({
  id: '/dashboard/accessibilite',
  path: '/dashboard/accessibilite',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$pageName': typeof PageNameRoute
  '/dashboard/accessibilite': typeof DashboardAccessibiliteRoute
  '/dashboard/devops': typeof DashboardDevopsRoute
  '/dashboard/greenit': typeof DashboardGreenitRoute
  '/dashboard/maturite': typeof DashboardMaturiteRoute
  '/dashboard/meteo': typeof DashboardMeteoRoute
  '/dashboard/overview': typeof DashboardOverviewRoute
  '/dashboard/qualite': typeof DashboardQualiteRoute
  '/dashboard/securite': typeof DashboardSecuriteRoute
  '/dashboard/synthese': typeof DashboardSyntheseRoute
  '/indicateur/accessibiliteTable': typeof IndicateurAccessibiliteTableRoute
  '/indicateur/devopsTable': typeof IndicateurDevopsTableRoute
  '/indicateur/greenITTable': typeof IndicateurGreenITTableRoute
  '/indicateur/mainIndicators': typeof IndicateurMainIndicatorsRoute
  '/indicateur/meteoTable': typeof IndicateurMeteoTableRoute
  '/indicateur/qualiteTable': typeof IndicateurQualiteTableRoute
  '/indicateur/securiteTable': typeof IndicateurSecuriteTableRoute
  '/indicateur/strategieCloudTable': typeof IndicateurStrategieCloudTableRoute
  '/saisie/accessibilité': typeof SaisieAccessibilitChar233Route
  '/saisie/meteo': typeof SaisieMeteoRoute
  '/saisie/strategiecloud': typeof SaisieStrategiecloudRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$pageName': typeof PageNameRoute
  '/dashboard/accessibilite': typeof DashboardAccessibiliteRoute
  '/dashboard/devops': typeof DashboardDevopsRoute
  '/dashboard/greenit': typeof DashboardGreenitRoute
  '/dashboard/maturite': typeof DashboardMaturiteRoute
  '/dashboard/meteo': typeof DashboardMeteoRoute
  '/dashboard/overview': typeof DashboardOverviewRoute
  '/dashboard/qualite': typeof DashboardQualiteRoute
  '/dashboard/securite': typeof DashboardSecuriteRoute
  '/dashboard/synthese': typeof DashboardSyntheseRoute
  '/indicateur/accessibiliteTable': typeof IndicateurAccessibiliteTableRoute
  '/indicateur/devopsTable': typeof IndicateurDevopsTableRoute
  '/indicateur/greenITTable': typeof IndicateurGreenITTableRoute
  '/indicateur/mainIndicators': typeof IndicateurMainIndicatorsRoute
  '/indicateur/meteoTable': typeof IndicateurMeteoTableRoute
  '/indicateur/qualiteTable': typeof IndicateurQualiteTableRoute
  '/indicateur/securiteTable': typeof IndicateurSecuriteTableRoute
  '/indicateur/strategieCloudTable': typeof IndicateurStrategieCloudTableRoute
  '/saisie/accessibilité': typeof SaisieAccessibilitChar233Route
  '/saisie/meteo': typeof SaisieMeteoRoute
  '/saisie/strategiecloud': typeof SaisieStrategiecloudRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$pageName': typeof PageNameRoute
  '/dashboard/accessibilite': typeof DashboardAccessibiliteRoute
  '/dashboard/devops': typeof DashboardDevopsRoute
  '/dashboard/greenit': typeof DashboardGreenitRoute
  '/dashboard/maturite': typeof DashboardMaturiteRoute
  '/dashboard/meteo': typeof DashboardMeteoRoute
  '/dashboard/overview': typeof DashboardOverviewRoute
  '/dashboard/qualite': typeof DashboardQualiteRoute
  '/dashboard/securite': typeof DashboardSecuriteRoute
  '/dashboard/synthese': typeof DashboardSyntheseRoute
  '/indicateur/accessibiliteTable': typeof IndicateurAccessibiliteTableRoute
  '/indicateur/devopsTable': typeof IndicateurDevopsTableRoute
  '/indicateur/greenITTable': typeof IndicateurGreenITTableRoute
  '/indicateur/mainIndicators': typeof IndicateurMainIndicatorsRoute
  '/indicateur/meteoTable': typeof IndicateurMeteoTableRoute
  '/indicateur/qualiteTable': typeof IndicateurQualiteTableRoute
  '/indicateur/securiteTable': typeof IndicateurSecuriteTableRoute
  '/indicateur/strategieCloudTable': typeof IndicateurStrategieCloudTableRoute
  '/saisie/accessibilité': typeof SaisieAccessibilitChar233Route
  '/saisie/meteo': typeof SaisieMeteoRoute
  '/saisie/strategiecloud': typeof SaisieStrategiecloudRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$pageName'
    | '/dashboard/accessibilite'
    | '/dashboard/devops'
    | '/dashboard/greenit'
    | '/dashboard/maturite'
    | '/dashboard/meteo'
    | '/dashboard/overview'
    | '/dashboard/qualite'
    | '/dashboard/securite'
    | '/dashboard/synthese'
    | '/indicateur/accessibiliteTable'
    | '/indicateur/devopsTable'
    | '/indicateur/greenITTable'
    | '/indicateur/mainIndicators'
    | '/indicateur/meteoTable'
    | '/indicateur/qualiteTable'
    | '/indicateur/securiteTable'
    | '/indicateur/strategieCloudTable'
    | '/saisie/accessibilité'
    | '/saisie/meteo'
    | '/saisie/strategiecloud'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$pageName'
    | '/dashboard/accessibilite'
    | '/dashboard/devops'
    | '/dashboard/greenit'
    | '/dashboard/maturite'
    | '/dashboard/meteo'
    | '/dashboard/overview'
    | '/dashboard/qualite'
    | '/dashboard/securite'
    | '/dashboard/synthese'
    | '/indicateur/accessibiliteTable'
    | '/indicateur/devopsTable'
    | '/indicateur/greenITTable'
    | '/indicateur/mainIndicators'
    | '/indicateur/meteoTable'
    | '/indicateur/qualiteTable'
    | '/indicateur/securiteTable'
    | '/indicateur/strategieCloudTable'
    | '/saisie/accessibilité'
    | '/saisie/meteo'
    | '/saisie/strategiecloud'
  id:
    | '__root__'
    | '/'
    | '/$pageName'
    | '/dashboard/accessibilite'
    | '/dashboard/devops'
    | '/dashboard/greenit'
    | '/dashboard/maturite'
    | '/dashboard/meteo'
    | '/dashboard/overview'
    | '/dashboard/qualite'
    | '/dashboard/securite'
    | '/dashboard/synthese'
    | '/indicateur/accessibiliteTable'
    | '/indicateur/devopsTable'
    | '/indicateur/greenITTable'
    | '/indicateur/mainIndicators'
    | '/indicateur/meteoTable'
    | '/indicateur/qualiteTable'
    | '/indicateur/securiteTable'
    | '/indicateur/strategieCloudTable'
    | '/saisie/accessibilité'
    | '/saisie/meteo'
    | '/saisie/strategiecloud'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PageNameRoute: typeof PageNameRoute
  DashboardAccessibiliteRoute: typeof DashboardAccessibiliteRoute
  DashboardDevopsRoute: typeof DashboardDevopsRoute
  DashboardGreenitRoute: typeof DashboardGreenitRoute
  DashboardMaturiteRoute: typeof DashboardMaturiteRoute
  DashboardMeteoRoute: typeof DashboardMeteoRoute
  DashboardOverviewRoute: typeof DashboardOverviewRoute
  DashboardQualiteRoute: typeof DashboardQualiteRoute
  DashboardSecuriteRoute: typeof DashboardSecuriteRoute
  DashboardSyntheseRoute: typeof DashboardSyntheseRoute
  IndicateurAccessibiliteTableRoute: typeof IndicateurAccessibiliteTableRoute
  IndicateurDevopsTableRoute: typeof IndicateurDevopsTableRoute
  IndicateurGreenITTableRoute: typeof IndicateurGreenITTableRoute
  IndicateurMainIndicatorsRoute: typeof IndicateurMainIndicatorsRoute
  IndicateurMeteoTableRoute: typeof IndicateurMeteoTableRoute
  IndicateurQualiteTableRoute: typeof IndicateurQualiteTableRoute
  IndicateurSecuriteTableRoute: typeof IndicateurSecuriteTableRoute
  IndicateurStrategieCloudTableRoute: typeof IndicateurStrategieCloudTableRoute
  SaisieAccessibilitChar233Route: typeof SaisieAccessibilitChar233Route
  SaisieMeteoRoute: typeof SaisieMeteoRoute
  SaisieStrategiecloudRoute: typeof SaisieStrategiecloudRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$pageName': {
      id: '/$pageName'
      path: '/$pageName'
      fullPath: '/$pageName'
      preLoaderRoute: typeof PageNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saisie/strategiecloud': {
      id: '/saisie/strategiecloud'
      path: '/saisie/strategiecloud'
      fullPath: '/saisie/strategiecloud'
      preLoaderRoute: typeof SaisieStrategiecloudRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saisie/meteo': {
      id: '/saisie/meteo'
      path: '/saisie/meteo'
      fullPath: '/saisie/meteo'
      preLoaderRoute: typeof SaisieMeteoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saisie/accessibilité': {
      id: '/saisie/accessibilité'
      path: '/saisie/accessibilité'
      fullPath: '/saisie/accessibilité'
      preLoaderRoute: typeof SaisieAccessibilitChar233RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indicateur/strategieCloudTable': {
      id: '/indicateur/strategieCloudTable'
      path: '/indicateur/strategieCloudTable'
      fullPath: '/indicateur/strategieCloudTable'
      preLoaderRoute: typeof IndicateurStrategieCloudTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indicateur/securiteTable': {
      id: '/indicateur/securiteTable'
      path: '/indicateur/securiteTable'
      fullPath: '/indicateur/securiteTable'
      preLoaderRoute: typeof IndicateurSecuriteTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indicateur/qualiteTable': {
      id: '/indicateur/qualiteTable'
      path: '/indicateur/qualiteTable'
      fullPath: '/indicateur/qualiteTable'
      preLoaderRoute: typeof IndicateurQualiteTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indicateur/meteoTable': {
      id: '/indicateur/meteoTable'
      path: '/indicateur/meteoTable'
      fullPath: '/indicateur/meteoTable'
      preLoaderRoute: typeof IndicateurMeteoTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indicateur/mainIndicators': {
      id: '/indicateur/mainIndicators'
      path: '/indicateur/mainIndicators'
      fullPath: '/indicateur/mainIndicators'
      preLoaderRoute: typeof IndicateurMainIndicatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indicateur/greenITTable': {
      id: '/indicateur/greenITTable'
      path: '/indicateur/greenITTable'
      fullPath: '/indicateur/greenITTable'
      preLoaderRoute: typeof IndicateurGreenITTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indicateur/devopsTable': {
      id: '/indicateur/devopsTable'
      path: '/indicateur/devopsTable'
      fullPath: '/indicateur/devopsTable'
      preLoaderRoute: typeof IndicateurDevopsTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indicateur/accessibiliteTable': {
      id: '/indicateur/accessibiliteTable'
      path: '/indicateur/accessibiliteTable'
      fullPath: '/indicateur/accessibiliteTable'
      preLoaderRoute: typeof IndicateurAccessibiliteTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/synthese': {
      id: '/dashboard/synthese'
      path: '/dashboard/synthese'
      fullPath: '/dashboard/synthese'
      preLoaderRoute: typeof DashboardSyntheseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/securite': {
      id: '/dashboard/securite'
      path: '/dashboard/securite'
      fullPath: '/dashboard/securite'
      preLoaderRoute: typeof DashboardSecuriteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/qualite': {
      id: '/dashboard/qualite'
      path: '/dashboard/qualite'
      fullPath: '/dashboard/qualite'
      preLoaderRoute: typeof DashboardQualiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/overview': {
      id: '/dashboard/overview'
      path: '/dashboard/overview'
      fullPath: '/dashboard/overview'
      preLoaderRoute: typeof DashboardOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/meteo': {
      id: '/dashboard/meteo'
      path: '/dashboard/meteo'
      fullPath: '/dashboard/meteo'
      preLoaderRoute: typeof DashboardMeteoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/maturite': {
      id: '/dashboard/maturite'
      path: '/dashboard/maturite'
      fullPath: '/dashboard/maturite'
      preLoaderRoute: typeof DashboardMaturiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/greenit': {
      id: '/dashboard/greenit'
      path: '/dashboard/greenit'
      fullPath: '/dashboard/greenit'
      preLoaderRoute: typeof DashboardGreenitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/devops': {
      id: '/dashboard/devops'
      path: '/dashboard/devops'
      fullPath: '/dashboard/devops'
      preLoaderRoute: typeof DashboardDevopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/accessibilite': {
      id: '/dashboard/accessibilite'
      path: '/dashboard/accessibilite'
      fullPath: '/dashboard/accessibilite'
      preLoaderRoute: typeof DashboardAccessibiliteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PageNameRoute: PageNameRoute,
  DashboardAccessibiliteRoute: DashboardAccessibiliteRoute,
  DashboardDevopsRoute: DashboardDevopsRoute,
  DashboardGreenitRoute: DashboardGreenitRoute,
  DashboardMaturiteRoute: DashboardMaturiteRoute,
  DashboardMeteoRoute: DashboardMeteoRoute,
  DashboardOverviewRoute: DashboardOverviewRoute,
  DashboardQualiteRoute: DashboardQualiteRoute,
  DashboardSecuriteRoute: DashboardSecuriteRoute,
  DashboardSyntheseRoute: DashboardSyntheseRoute,
  IndicateurAccessibiliteTableRoute: IndicateurAccessibiliteTableRoute,
  IndicateurDevopsTableRoute: IndicateurDevopsTableRoute,
  IndicateurGreenITTableRoute: IndicateurGreenITTableRoute,
  IndicateurMainIndicatorsRoute: IndicateurMainIndicatorsRoute,
  IndicateurMeteoTableRoute: IndicateurMeteoTableRoute,
  IndicateurQualiteTableRoute: IndicateurQualiteTableRoute,
  IndicateurSecuriteTableRoute: IndicateurSecuriteTableRoute,
  IndicateurStrategieCloudTableRoute: IndicateurStrategieCloudTableRoute,
  SaisieAccessibilitChar233Route: SaisieAccessibilitChar233Route,
  SaisieMeteoRoute: SaisieMeteoRoute,
  SaisieStrategiecloudRoute: SaisieStrategiecloudRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
