/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DevopsTableRouteImport } from './routes/devopsTable'
import { Route as IndexRouteImport } from './routes/index'

const DevopsTableRoute = DevopsTableRouteImport.update({
  id: '/devopsTable',
  path: '/devopsTable',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/devopsTable': typeof DevopsTableRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/devopsTable': typeof DevopsTableRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/devopsTable': typeof DevopsTableRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/devopsTable'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/devopsTable'
  id: '__root__' | '/' | '/devopsTable'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DevopsTableRoute: typeof DevopsTableRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/devopsTable': {
      id: '/devopsTable'
      path: '/devopsTable'
      fullPath: '/devopsTable'
      preLoaderRoute: typeof DevopsTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DevopsTableRoute: DevopsTableRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
