/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IndicateurDevopsTableRouteImport } from './routes/indicateur/devopsTable'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IndicateurDevopsTableRoute = IndicateurDevopsTableRouteImport.update({
  id: '/indicateur/devopsTable',
  path: '/indicateur/devopsTable',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/indicateur/devopsTable': typeof IndicateurDevopsTableRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/indicateur/devopsTable': typeof IndicateurDevopsTableRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/indicateur/devopsTable': typeof IndicateurDevopsTableRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/indicateur/devopsTable'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/indicateur/devopsTable'
  id: '__root__' | '/' | '/indicateur/devopsTable'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IndicateurDevopsTableRoute: typeof IndicateurDevopsTableRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indicateur/devopsTable': {
      id: '/indicateur/devopsTable'
      path: '/indicateur/devopsTable'
      fullPath: '/indicateur/devopsTable'
      preLoaderRoute: typeof IndicateurDevopsTableRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IndicateurDevopsTableRoute: IndicateurDevopsTableRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
